# Generated by Django 4.2.4 on 2023-11-17 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_saving',
            name='user_id',
            field=models.ManyToManyField(related_name='lsaving', to=settings.AUTH_USER_MODEL),
        ),
    ]
